### ISSUE TITLE
Managed Classes and Triggers causing NullPointerException

### ISSUE THREAD

**Issue by banderson5144** [yebihara/ApexTestPlus#1]
Hey. I really like this tool. I think it is very useful for automating testmethods and seeing code coverage. There is only one problem I see with it so far. Managed Classes and Trigger from Managed Packages.

A test I ran to confirm this was to create a dev account and create some classes with some testmethods and no installed Packages. Your tool ran perfectly. However, when i installed "EasyDescibe", a managed package with no visibility to classes or triggers, when i ran the tool again i got a null pointer exception:

BUILD FAILED
build.xml:86: java.lang.NullPointerException
        at com.force.jp.ant.apextestplus.TestResult.genCoverageResultsHtml(Unknown Source)
        at com.force.jp.ant.apextestplus.TestResult.visualizeCoverageResults(Unknown Source)
        at com.force.jp.ant.apextestplus.RunTestTask.execute(Unknown Source)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:392)
        at org.apache.tools.ant.Target.performTasks(Target.java:413)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:811)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

What i think maybe happening is this. When I ran the metadata API call to Salesforce to runAllTests, it kicked back a portion of XML that was referring to one of the managed classes and telling where exact lines were skipped:

<codeCoverage>
               <id>01pE0000001fPVhIAM</id>
               <locationsNotCovered>
                  <column>0</column>
                  <line>75</line>
                  <numExecutions>0</numExecutions>
                  <time>-1.0</time>
               </locationsNotCovered>
               <locationsNotCovered>
                  <column>0</column>
                  <line>77</line>
                  <numExecutions>0</numExecutions>
                  <time>-1.0</time>
               </locationsNotCovered>
               <locationsNotCovered>
                  <column>0</column>
                  <line>88</line>
                  <numExecutions>0</numExecutions>
                  <time>-1.0</time>
               </locationsNotCovered>
               <locationsNotCovered>
                  <column>0</column>
                  <line>89</line>
                  <numExecutions>0</numExecutions>
                  <time>-1.0</time>
               </locationsNotCovered>
               <locationsNotCovered>
                  <column>0</column>
                  <line>90</line>
                  <numExecutions>0</numExecutions>
                  <time>-1.0</time>
               </locationsNotCovered>
               <name>DescribeObjectCon</name>
               <namespace>EasyDescribe</namespace>
               <numLocations>50</numLocations>
               <numLocationsNotCovered>5</numLocationsNotCovered>
               <type>Class</type>
            </codeCoverage>

However, when you look at the actual class that was downloaded, the only thing inside of it was:

(hidden)

So i think the problem is when you are trying to highlight the missing Line number and you dont see it, it throws a null pointer exception.

The way Salesforce handles this in there UI is to not let the user see the Line missing Hit UI, they do not create a Hyperlink for the Code Coverage Percentage for managed classes or triggers.

I think if you just create a condition where if the class is managed or has "(hidden)" as its content, just report its code coverage percentage and not show the associated Debug log for it and not show the Line Graph thing, then you are in business.

Thanks I hope you can get this done soon!

**Comment by yebihara** [comment]
Thank you for your reporting the issue.
I'm happy to know that at least one person is using this tool! :-)

I'm going to try to reproduce and resolve it.
I'll be back later.

**Comment by banderson5144** [comment]
Thanks very much. Sooner the better! :P

**Comment by banderson5144** [comment]
Hey, I have one question. How would I set up this project in eclipse to use JIT debugging? Maybe I can take a crack at it.

**Comment by yebihara** [comment]
I've resolved this issue.

Regarding JIT debugging, I've never used it and have no idea.
If you file a new issue and leave it open, someone else may find it and help you in the future...

**Comment by banderson5144** [comment]
So looking through your code you basically did the same i did to get it to work (A couple of System.out.println showed me the root of the problem). Just one thing I want to mention though is that for the namespace you are only checking for null. I ran into a problem yesterday where I got an empty string for a namespace and null for the name of the class:

&lt;codeCoverageWarnings&gt;<br/>               &lt;id&gt;01qF0000000eglWIAQ&lt;/id&gt;<br/>               &lt;message&gt;Average test coverage across all Apex Classes and Triggers is 24%, at least 75% test coverage is required.&lt;/message&gt;<br/>               &lt;name xsi:nil=&quot;true&quot;/&gt;<br/>               &lt;namespace/&gt;<br/>            &lt;/codeCoverageWarnings&gt;

So in your ternary check, i would also do empty strings as well. But thanks again for looking into this and creating this wonderful tool!

Just one last question though, are you using the Metadata API call runTest or the Apex API call runTest?

**Comment by yebihara** [comment]
Good catch!
Thanks!

> Just one last question though, are you using the Metadata API call runTest or the Apex API call runTest?

This software fully depends on classes that Force.com Migration Tool provides when it sends any request.
And I believe Metadata API is used.

**Comment by meramo64** [comment]
I recently downloaded ApexTestPlus. It is great...thanks you!  I am however running into Null Pointer exceptions with certain classes (same as the issue above). Were there any updates applied to get around this issue? I am using version 30.0 (Spring 14).

Thanks

**Comment by yebihara** [comment]
Hi @meramo64 ,

Thank you for your feedback.
Can you give me the exact Java exception with call stack?
Also, since I'm not aware if your case is the same issue as this, I'm afraid I want you to open a new issue.

**Comment by meramo64** [comment]
Hi @yebihara,
    Here is the exception I run into. I only get this with certain classes but I am thinking it might be the same as the issue above:

[apextestplus:runTest] java.lang.NullPointerException
[apextestplus:runTest]  at java.util.TreeMap.getEntry(TreeMap.java:324)
[apextestplus:runTest]  at java.util.TreeMap.get(TreeMap.java:255)
[apextestplus:runTest]  at com.force.jp.ant.apextestplus.TestResult.separateDebugLog(TestResult.java:187)
[apextestplus:runTest]  at com.force.jp.ant.apextestplus.RunTestTask.execute(RunTestTask.java:76)
[apextestplus:runTest]  at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[apextestplus:runTest]  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[apextestplus:runTest]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[apextestplus:runTest]  at java.lang.reflect.Method.invoke(Method.java:597)
[apextestplus:runTest]  at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[apextestplus:runTest]  at org.apache.tools.ant.Task.perform(Task.java:348)
[apextestplus:runTest]  at org.apache.tools.ant.Target.execute(Target.java:435)
[apextestplus:runTest]  at org.apache.tools.ant.Target.performTasks(Target.java:456)
[apextestplus:runTest]  at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[apextestplus:runTest]  at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[apextestplus:runTest]  at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[apextestplus:runTest]  at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[apextestplus:runTest]  at org.apache.tools.ant.Main.runBuild(Main.java:851)
[apextestplus:runTest]  at org.apache.tools.ant.Main.startAnt(Main.java:235)
[apextestplus:runTest]  at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[apextestplus:runTest]  at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

BTW this tool looks really helpful and I hope to be able to test it further. 
If you prefer I open a new case, please let me know. 

Thanks!

**Comment by yebihara** [comment]
Hi @meramo64 ,

Thank you for your response.
As far as I see the stack trace, the NullPointerException is caused by a different problem.
So I filed a new issue, #2 .
Let's discuss further things on #2 .

Thanks!
